name: Backend Qodana

on:
    pull_request:
        branches: [main, development]
        paths:
            - "backend/**"
    push:
        branches: [development]
        paths:
            - "backend/**"

jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write

        steps:
            - uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.sha }}
                  fetch-depth: 0

            - name: Qodana Scan
              uses: JetBrains/qodana-action@v2026.1
              with:
                  args: --config qodana-backend.yaml
                  pr-mode: false
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_BACKEND }}
                  QODANA_ENDPOINT: https://qodana.cloud
